kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: "/var/nfs/openshift/test"
    server: "172.16.24.246"
    readOnly: false