kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  volumeName: test-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi